// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATs9eJphlG2RlkRSaBcGFhDLkuA6NG0Xs',
    appId: '1:398730560250:web:046869ad0b62c639253f43',
    messagingSenderId: '398730560250',
    projectId: 'final-pracitice-tiktok',
    authDomain: 'final-pracitice-tiktok.firebaseapp.com',
    storageBucket: 'final-pracitice-tiktok.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFjj4zk8t-CFBbGNbO2-uKjdOtRHVVCJk',
    appId: '1:398730560250:android:591817ef8107d7e9253f43',
    messagingSenderId: '398730560250',
    projectId: 'final-pracitice-tiktok',
    storageBucket: 'final-pracitice-tiktok.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNi9aN-c4LZl394b5kOzNKSfWc9IZg69k',
    appId: '1:398730560250:ios:d293d5a362e2f151253f43',
    messagingSenderId: '398730560250',
    projectId: 'final-pracitice-tiktok',
    storageBucket: 'final-pracitice-tiktok.appspot.com',
    iosBundleId: 'com.example.project',
  );
}
